let tasks=[], user=null, csrf="", activeFilter="all";
const $=s=>document.querySelector(s);
const esc=s=>(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const fmt=d=>d?d.split("-").reverse().join("/"):"";
function toast(msg){$("#toast").textContent=msg;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),3000)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),"Content-Type":"application/json"};if(csrf)opt.headers["X-CSRF-Token"]=csrf;let r=await fetch(url,opt),j=await r.json().catch(()=>({ok:false,error:"Resposta inválida"}));if(!r.ok)throw new Error(j.error||"Erro");return j}
async function boot(){try{let j=await api("api/auth.php?action=me");if(j.user){user=j.user;csrf=j.csrf;showApp();await loadTasks()}else showAuth()}catch(e){toast("Não foi possível conectar ao servidor.")}}
function showAuth(){$("#authView").classList.remove("hidden");$("#appView").classList.add("hidden")}
function showApp(){$("#authView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#welcome").textContent=`Olá, ${user.name}. Suas tarefas estão sincronizadas.`}
document.querySelectorAll("[data-auth-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#loginForm").classList.toggle("hidden",b.dataset.authTab!=="login");$("#registerForm").classList.toggle("hidden",b.dataset.authTab!=="register")});
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{let j=await api("api/auth.php?action=login",{method:"POST",body:JSON.stringify({email:$("#loginEmail").value,password:$("#loginPassword").value})});user=j.user;csrf=j.csrf;showApp();await loadTasks()}catch(x){toast(x.message)}};
$("#registerForm").onsubmit=async e=>{e.preventDefault();try{let j=await api("api/auth.php?action=register",{method:"POST",body:JSON.stringify({name:$("#registerName").value,email:$("#registerEmail").value,password:$("#registerPassword").value})});user=j.user;csrf=j.csrf;showApp();await loadTasks()}catch(x){toast(x.message)}};
$("#logoutBtn").onclick=async()=>{try{await api("api/auth.php?action=logout",{method:"POST",body:"{}"});tasks=[];user=null;csrf="";showAuth()}catch(x){toast(x.message)}};
async function loadTasks(){try{let j=await api("api/tasks.php");tasks=j.tasks;csrf=j.csrf;render()}catch(x){if(x.message==="Não autenticado")showAuth();else toast(x.message)}}
function resetForm(){$("#taskForm").reset();$("#taskId").value="";$("#priority").value="media";$("#formTitle").textContent="Nova tarefa";$("#cancelEdit").classList.add("hidden")}
$("#cancelEdit").onclick=resetForm;
$("#taskForm").onsubmit=async e=>{e.preventDefault();let id=$("#taskId").value,data={id:Number(id)||undefined,title:$("#title").value.trim(),description:$("#description").value.trim(),dueDate:$("#dueDate").value,priority:$("#priority").value,category:$("#category").value.trim(),done:id?(tasks.find(t=>String(t.id)===id)?.done||false):false};try{await api("api/tasks.php",{method:id?"PUT":"POST",body:JSON.stringify(data)});resetForm();await loadTasks();toast(id?"Tarefa atualizada.":"Tarefa criada.")}catch(x){toast(x.message)}};
function edit(id){let t=tasks.find(x=>String(x.id)===String(id));if(!t)return;$("#taskId").value=t.id;$("#title").value=t.title;$("#description").value=t.description||"";$("#dueDate").value=t.dueDate||"";$("#priority").value=t.priority;$("#category").value=t.category||"";$("#formTitle").textContent="Editar tarefa";$("#cancelEdit").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
async function remove(id){if(!confirm("Excluir esta tarefa?"))return;try{await api("api/tasks.php",{method:"DELETE",body:JSON.stringify({id:Number(id)})});await loadTasks()}catch(x){toast(x.message)}}
async function toggle(id){let t=tasks.find(x=>String(x.id)===String(id));if(!t)return;try{await api("api/tasks.php",{method:"PUT",body:JSON.stringify({...t,id:Number(t.id),done:!t.done})});await loadTasks()}catch(x){toast(x.message)}}
document.addEventListener("click",e=>{let b=e.target.closest("[data-action]");if(b){if(b.dataset.action==="edit")edit(b.dataset.id);if(b.dataset.action==="delete")remove(b.dataset.id)}});document.addEventListener("change",e=>{if(e.target.matches(".check"))toggle(e.target.dataset.id)});
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeFilter=b.dataset.filter;render()});$("#search").oninput=render;$("#sort").onchange=render;
function visible(){let q=$("#search").value.toLowerCase().trim(),td=today(),a=tasks.filter(t=>{let text=`${t.title} ${t.description||""} ${t.category||""}`.toLowerCase();return(!q||text.includes(q))&&(activeFilter!=="pending"||!t.done)&&(activeFilter!=="done"||t.done)&&(activeFilter!=="today"||t.dueDate===td)}),w={alta:3,media:2,baixa:1};a.sort((x,y)=>$("#sort").value==="due"?(x.dueDate||"9999").localeCompare(y.dueDate||"9999"):$("#sort").value==="priority"?(w[y.priority]-w[x.priority]):String(y.createdAt).localeCompare(String(x.createdAt)));return a}
function render(){let td=today();$("#totalCount").textContent=tasks.length;$("#pendingCount").textContent=tasks.filter(t=>!t.done).length;$("#doneCount").textContent=tasks.filter(t=>t.done).length;$("#todayCount").textContent=tasks.filter(t=>!t.done&&t.dueDate===td).length;let a=visible();$("#emptyState").classList.toggle("hidden",!!a.length);$("#taskList").innerHTML=a.map(t=>{let late=t.dueDate&&t.dueDate<td&&!t.done;return `<article class="task ${t.done?"done":""}"><input class="check" data-id="${t.id}" type="checkbox" ${t.done?"checked":""}><div><h3>${esc(t.title)}</h3>${t.description?`<p>${esc(t.description)}</p>`:""}<div class="meta">${t.dueDate?`<span class="badge ${late?"overdue":""}">${late?"Atrasada · ":""}${fmt(t.dueDate)}</span>`:""}<span class="badge">Prioridade ${esc(t.priority)}</span>${t.category?`<span class="badge">${esc(t.category)}</span>`:""}</div></div><div class="actions"><button data-action="edit" data-id="${t.id}">✎</button><button class="delete" data-action="delete" data-id="${t.id}">×</button></div></article>`}).join("")}
function theme(t){document.body.classList.toggle("dark",t==="dark");$("#themeBtn").textContent=t==="dark"?"☀":"☾";localStorage.setItem("tasks_theme",t)}$("#themeBtn").onclick=()=>theme(document.body.classList.contains("dark")?"light":"dark");theme(localStorage.getItem("tasks_theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"));boot();