let tasks=[],user=null,csrf="",filter="all";const $=s=>document.querySelector(s),esc=s=>(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function api(u,o={}){o.headers={...(o.headers||{}),"Content-Type":"application/json"};if(csrf)o.headers["X-CSRF-Token"]=csrf;let r=await fetch(u,{...o,cache:"no-store"}),t=await r.text(),j;try{j=JSON.parse(t)}catch{throw Error("Resposta PHP inválida. Confira config.php.")}if(!r.ok||j.ok===false)throw Error(j.error||"Erro no servidor");return j}
function err(m){$("#error").textContent=m;$("#error").classList.remove("hide")}function clear(){ $("#error").classList.add("hide")}
async function boot(){try{let h=await api("api/auth.php?action=health");$("#health").textContent=h.tables?"✓ MySQL conectado e tabelas encontradas":"✕ MySQL conectado, mas faltam tabelas";$("#health").className="health "+(h.tables?"ok":"bad")}catch(e){$("#health").textContent="✕ "+e.message;$("#health").className="health bad";err(e.message)}try{let j=await api("api/auth.php?action=me");if(j.user){user=j.user;csrf=j.csrf;showApp();load()}}catch(e){}}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{clear();document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));b.classList.add("on");let r=b.dataset.tab==="register";$("#login").classList.toggle("hide",r);$("#register").classList.toggle("hide",!r)});
$("#register").onsubmit=async e=>{e.preventDefault();clear();try{let j=await api("api/auth.php?action=register",{method:"POST",body:JSON.stringify({name:$("#rn").value,email:$("#re").value,password:$("#rp").value})});user=j.user;csrf=j.csrf;showApp();load()}catch(e){err(e.message)}};
$("#login").onsubmit=async e=>{e.preventDefault();clear();try{let j=await api("api/auth.php?action=login",{method:"POST",body:JSON.stringify({email:$("#le").value,password:$("#lp").value})});user=j.user;csrf=j.csrf;showApp();load()}catch(e){err(e.message)}};
function showApp(){$("#auth").classList.add("hide");$("#app").classList.remove("hide");$("#welcome").textContent="Olá, "+user.name+". Seus dados estão sincronizados."}
$("#logout").onclick=async()=>{try{await api("api/auth.php?action=logout",{method:"POST",body:"{}"})}catch{}location.reload()};
async function load(){let j=await api("api/tasks.php");tasks=j.tasks;csrf=j.csrf;render()}
function reset(){$("#task").reset();$("#id").value="";$("#ft").textContent="Nova tarefa";$("#cancel").classList.add("hide")}$("#cancel").onclick=reset;
$("#task").onsubmit=async e=>{e.preventDefault();let id=$("#id").value,t=tasks.find(x=>String(x.id)===id),d={id:+id||undefined,title:$("#title").value,description:$("#desc").value,dueDate:$("#date").value,priority:$("#priority").value,category:$("#cat").value,done:t?.done||false};try{await api("api/tasks.php",{method:id?"PUT":"POST",body:JSON.stringify(d)});reset();load()}catch(e){alert(e.message)}};
document.addEventListener("click",async e=>{let b=e.target.closest("[data-a]");if(!b)return;let t=tasks.find(x=>String(x.id)===b.dataset.id);if(b.dataset.a==="edit"){$("#id").value=t.id;$("#title").value=t.title;$("#desc").value=t.description||"";$("#date").value=t.dueDate||"";$("#priority").value=t.priority;$("#cat").value=t.category||"";$("#ft").textContent="Editar tarefa";$("#cancel").classList.remove("hide");scrollTo(0,0)}else if(b.dataset.a==="del"&&confirm("Excluir esta tarefa?")){await api("api/tasks.php",{method:"DELETE",body:JSON.stringify({id:+t.id})});load()}else if(b.dataset.a==="toggle"){await api("api/tasks.php",{method:"PUT",body:JSON.stringify({...t,id:+t.id,done:!t.done})});load()}});
document.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("on"));b.classList.add("on");filter=b.dataset.f;render()});$("#search").oninput=render;$("#sort").onchange=render;
function render(){let td=new Date().toLocaleDateString("en-CA"),q=$("#search").value.toLowerCase(),a=tasks.filter(t=>(!q||(`${t.title} ${t.description||""} ${t.category||""}`).toLowerCase().includes(q))&&(filter!=="pending"||!t.done)&&(filter!=="done"||t.done)&&(filter!=="today"||t.dueDate===td));$("#total").textContent=tasks.length;$("#pending").textContent=tasks.filter(t=>!t.done).length;$("#done").textContent=tasks.filter(t=>t.done).length;$("#today").textContent=tasks.filter(t=>!t.done&&t.dueDate===td).length;$("#list").innerHTML=a.map(t=>`<article class="task ${t.done?"done":""}"><button data-a="toggle" data-id="${t.id}">${t.done?"✓":"○"}</button><div><h3>${esc(t.title)}</h3><p>${esc(t.description||"")}</p><div class="meta">${t.dueDate||""} · ${esc(t.priority)} ${t.category?"· "+esc(t.category):""}</div></div><div class="actions"><button data-a="edit" data-id="${t.id}">✎</button><button data-a="del" data-id="${t.id}">×</button></div></article>`).join("")}
function theme(t){document.body.classList.toggle("dark",t==="dark");$("#theme").innerHTML=t==="dark"?'☀️ <span>Tema claro</span>':'🌙 <span>Tema escuro</span>';localStorage.setItem("tarefas_theme",t)}$("#theme").onclick=()=>theme(document.body.classList.contains("dark")?"light":"dark");theme(localStorage.getItem("tarefas_theme")||"light");boot();